[satellites]
sat0.os = "Kubos v1.18.3, Kernel: 5.4.0-74-generic"
sat0.version = "v1.1.3"
sat0.debug_mode = false
sat0.password = "openup"
sat0.shutdown_code = 0

sat1.os = "Kubos v1.18.3, Kernel: 5.4.0-74-generic"
sat1.version = "v1.1.3"
sat1.debug_mode = false
sat1.password = "sillygoose"
sat1.shutdown_code = 0

sat2.os = "Kubos v1.18.3, Kernel: 5.4.0-74-lowlatency"
sat2.version = "v1.1.2"
sat2.debug_mode = false
sat2.password = "pkss2bmlkdztlK7i"
sat2.connection_limit = 1
sat2.shutdown_code = 1882

sat3.os = "Kubos v1.18.3, Kernel: 5.4.0-74-lowlatency"
sat3.version = "v1.1.3"
sat3.debug_mode = true
sat3.debug_ip = "sat0"
sat3.password = "0FmG7AZIWsxc7f8PxWI3" # this is in the intel packet
sat3.connection_limit = 100
sat3.shutdown_code = 1105

sat4.os = "Kubos v1.21.0, Kernel: 5.4.0-74-lowlatency"
sat4.version = "v2.1.5"
sat4.debug_mode = false
sat4.password = "sempersupra"
sat4.shutdown_code = 5501